on:
  push:
    branches:
      - main

jobs:
  post_tweet_job:
    runs-on: ubuntu-latest
    name: Post tweet to Twitter
    steps:
      - name: Tweets contents of PR
        uses: ../actions
        with:
          consumer-key: ${{ secrets.TWITTER_CONSUMER_KEY }}
          consumer-secret: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          access-token: ${{ secrets.TWITTER_ACCESS_TOKEN_KEY }}
          access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
